### ISSUE TITLE
GitHub description change

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#1]
Hello Eric!
Can you change GiHub title from:
_Multi Tabbed Putty_
to a more descriptive name like:
_Multi Tabbed Putty wrote in Java_
?
I think can add more people interested on this great project.

**Comment by ericmore** [comment]
Sure, updated now

**Comment by crisistotal2014** [comment]
Thank so much, Eric!
With this I'll hope more people will found SmartPutty and try to use and improve it.

Great!
