### ISSUE TITLE
Remove unused JAR libraries

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#10]
Hello Eric!
Is possible to remove unused JAR libraries? Seems that following libraries are no longer used:
- org.eclipse.core.commands_3.6.1.v20120521-2329.jar
- org.eclipse.equinox.common_3.6.100.v20120522-1841.jar
- org.eclipse.ui.forms_3.5.200.v20120521-2329.jar

Thanks in advance!

**Comment by ericmore** [comment]
Already remove the unused jar...  
Gradle setup finished.
It's possible to use  "gradle build" to build project and distribute to "SmartPutty\build\distributions\SmartPutty.zip"   
unzip it and cd into SmartPutty.
Run "java -jar SmartPutty.jar"  from command line will startup this project.

**Comment by crisistotal2014** [comment]
Thanks!
"swt-3.5.0.jar" library is needed?

**Comment by ericmore** [comment]
Hi Carlos,
I removed the lib dir, I think it's not necessary since we use gradle for
lib dependency management.

I am using Intellij IDEA,  not sure if you are using eclipse.  let me know
if everything works the same in eclipse

2017-09-29 17:46 GMT+08:00 Carlos SS <notifications@github.com>:

**Comment by crisistotal2014** [comment]
Thanks Eric!
I'm using NetBeans 8 to develop in Java, and I should learn how to work with Gradle and libraries.
