### ISSUE TITLE
Add close capability to new lower toolbar

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#11]
Hi!
Is possible to add close capability to new lower toolbar? Many screens are litle and this toolbar is taking space.
Or also, can you offer a emerging toolbar(raising up when mouse pointer is near him, and auto-hidding)?

Personally I don't need it.

(Feel free to close this issue when done)

**Comment by ericmore** [comment]
Just do the same as quick connector bar.  User can config it under "view" menu
