### ISSUE TITLE
Replace internal proprietary API "Base64Util" class with "Apache Commons Codec 1.10 API"

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#14]
Hello Eric!
Is possibel to replace internal proprietary API "Base64Util" class with "Apache Commons Codec API"?
I think you like "Apache API's" (well done!) and "Apache Commons Codec API" seems a good alternative to remove compillation warnings like:

SmartPutty\src\Dao\Base64Util.java:3: warning: BASE64Decoder is internal proprietary API and may be removed in a future release
import sun.misc.BASE64Decoder;

With this our code will be more stronger.

(Feel free to close when done)

**Comment by ericmore** [comment]
Done,  removed Base64Util.java
replaced with commons-codec-1.9.jar
