### ISSUE TITLE
"commons-net-1.2.2.jar" library not needed

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#15]
Hello Eric!
Seem "commons-net-1.2.2.jar" library is not needed ("dev" branch).

Please, can you check-it and delete-it?

Thanks!

**Comment by crisistotal2014** [comment]
Sorry. I did a mistake.

**Comment by ericmore** [comment]
sure, will check it after work .  we have a firewall inside firm :)
