### ISSUE TITLE
Remove Gradle support

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#22]
Hi Eric!
This is Carlos another time  :-D  How are you? So many time from last collaborations!!

I have a simple question: is possible to remove Gradle support on this project? Main reason is that is so many difficult to use Gradle on another IDE's (like NetBeans). Yesterday I've accomplished to work on NetBeans, but this can be an stopper to work on this project for another people.

I consider we must keep simple things. What do you think?

**Comment by ericmore** [comment]
Hi Carlos,
Remove gradle is simple, however it will be strange to revert it back.
Construct tool like maven, gradle are much easier then without it
Netbean is easy to config gradle plugin, right ?
https://examples.javacodegeeks.com/core-java/gradle/gradle-netbeans-example/


Carlos SS <notifications@github.com> 于2019年4月10日周三 下午2:36写道：

**Comment by crisistotal2014** [comment]
Sure! I've followed same document to setup Gradle.  But I think this isn't a big project to need Gradle nor Maven.
Also you've been working on SmartPutty since some years and no one join us to develop this great software. I don't want die of SmartPutty.

What we can do?

**Comment by crisistotal2014** [comment]
OK, you are in reason. I close due New State of things ;-)
