### ISSUE TITLE
SWT library defined in Gradle config file is for 64 bits only

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#24]
Hi Eric:
I've another mistake due Gradle. My workstation is 32 bits, and I can't compile your program due Gradle it's configured to use only 64 bits version of SWT library.

To get my compilation to work I used this line (on build.gradle file):
   compile group: 'org.eclipse.swt', name: 'org.eclipse.swt.win32.win32.x86', version: '4.3'
instead of:
compile group: 'org.eclipse.swt', name: 'org.eclipse.swt.win32.win32.x86_64', version: '4.3'

P.D.:
I found this piece of Gradle code which can help to detect architecture, but I don't known how to implement:
```
model {
    platforms {
        x86 {
            architecture "x86"
        }
        x64 {
            architecture "x86_64"
        }
    }
}
model {
    components {
        main(NativeLibrarySpec) {
            targetPlatform "x86"
            targetPlatform "x64"
        }
    }
}
```

**Comment by ericmore** [comment]
Dear Carlos， glad to hear you again. wondering we could package
smartputty.jar in code，however jdk is a bit large do you think it is
necessary to incorporate jdk in repo？ BTW I am thinking whether i need to
support 32bit（modern pc are all 64bit）

Carlos SS <notifications@github.com>于2020年9月24日 周四上午2:46写道：

**Comment by crisistotal2014** [comment]
Nice also to hear you Eric, better in this pandemic times!! :-D 
Thank you to continue in front of this project!

Related to your replies, I don't understand "incorporate jdk in repo".
This issue is related only to 32/64 bits SWT library problem. In business environments is normal to have 64 bits PC, but in house some people can have an older 32 bits PC (like me). Solve this issue isn't problematic: this morning I've developed attached solution which works well for 32 bits.

Do you can evaluate, and merge if looks good for you?
[build.gradle.zip](https://github.com/ericmore/SmartPutty/files/5274757/build.gradle.zip)

**Comment by crisistotal2014** [comment]
Contents fixed on "gradle_fixes" branch (once merged this branch can be deleted).
