### ISSUE TITLE
Missing images on main page and on wiki page

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#30]
Hi Eric:
We've a great issue: images have been dissapeared from main page (https://github.com/ericmore/SmartPutty), and from wiki pages.

Please, can you try to find and restore it? We're losing hundred of clients every day :-)

Thanks!

**Comment by ericmore** [comment]
I moved the resource to #31, due to there is no storage in github store, unless I paid for some cloud storage service like AWS S3.
So I decide to upload resource file into a single issue which will permanent live

**Comment by crisistotal2014** [comment]
Great Eric! Main screen returned and a lot of possible client will see which face have your program.

Thank so much!
