### ISSUE TITLE
Window to define which programs to use

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#4]
Hi Eric!
I'll like to have a window to define which programs to use Putty/KiTTY, WinScp/Filezilla, etc., and save this values on configuration file

What do you think? Can I try it?

**Comment by ericmore** [comment]
could you describe it more detail ?  In my thought,  I regard the programs are now fixed by Java hardcoded.  If we want to give end user alternative program(exe) to use,  then what's the scenario and which program we should provide to user to let him config

**Comment by crisistotal2014** [comment]
Sorry Eric, I explained in a very bad way.
I want suggest to you to continue using your included programs (Putty and WinScp), but allow end user to use KiTTY or Filezilla in place of them (using my new class "Program"). This "replaceable" programs use same parameters and this doesn't do problems.
In a first stage this isn't intended for replace "Calculator", "VNC" or his neighboors on left bar, only for similiar programs, like Putty/KiTTY, WinScp/Filezilla.

**Comment by ericmore** [comment]
give alternative for end user with Putty -> Kitty , WinScp -> Filezilla ... Sounds good idea, if the parameters are very similiar...  I think you can have a try ...  I am concerning KiTTY, we are trying to invoke windows handle from swt os interface, Please go head to see whether KiTTY is workable for SmartPutty, at the same time, does KiTTY will have the portable version so that we can store exe inside our release package like putty.exe ?

**Comment by crisistotal2014** [comment]
Thanks so much much Eric!
I'll try to give an alternative. An yes: KiTTY is 100% portable like Putty.

**Comment by crisistotal2014** [comment]
Hello Eric!
Several days without news from me, sorry  :-p
I've a running version with a window to define putty/kitty and plink/klink. I'll try to upload via GIT.

**Comment by crisistotal2014** [comment]
Version uploaded!
Please, check-out and let me known your opinion.

**Comment by crisistotal2014** [comment]
I was wrong thinking about FileZilla supports "SCP", and not, it doesn't support.
Can I add support to define "Notepad" and "Screen Capture" programs? (they are simple programs without needed arguments)

**Comment by ericmore** [comment]
Hi, Will WinScp/Filezilla, etc still planned to be defined in customized window ?

**Comment by crisistotal2014** [comment]
Sure!
This will allow also to use embeded version, or a never version user owned.

**Comment by crisistotal2014** [comment]
I think we can close this issue due window was implemented.
