### ISSUE TITLE
Add version number to SmartPutty

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#5]
Hello!
Is possible to add a version number to SmartPutty (in title bar, in welcome page, etc.)?

This will add users to known in which version we are, and will track our archivements.

**Comment by ericmore** [comment]
Add VERSION file, and show it on mainframe title

**Comment by crisistotal2014** [comment]
Ey! You take me my budget!!!   :-D
I was thinking on using Configuration.xml file to store it. Is a bad idea or your prefer this new file VERSION?

**Comment by ericmore** [comment]
As my very first thinking, configuration file will be finally dynamically read/modify/override file.  As for version, that's a hard coded number string which should always maintain by us, no UI entry should touch OR edit that file... For the VERSION file's idea is from https://github.com/pubnub/java ...

Basically, I haven't found a standard way to store version, will it make more sense we use maven to control project.version?  Could you find any existing sample for PC Application Version design?

**Comment by crisistotal2014** [comment]
Sorry, you're are in reason. A VERSION file seems enough at this stage.
And no: I don't known PC Application Version design.
