### ISSUE TITLE
Hide "Welcome Page" on startup

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#6]
Hello Eric!
Since many times running SmartPutty I've detected "Welcome Page" tab isn't needed more (use instructions are easy and knowned for any user). After several times It's nice begin SmartPutty in a clean way.

What do you think about setting another configuration to hide it?
Perhaps, adding a new check item called "Show Welcome Page on start" under "View"?

**Comment by ericmore** [comment]
You are right , force user to see the screen everytime is really not a good way.
I suggest, let put a checkbox somewhere telling "Do not show Welcome next time".  Like most of applications , popup dialog will show to user, however he can disable it via check on 'Do not show it next time'

**Comment by crisistotal2014** [comment]
Are you saying to put a popup with a checkbox "Do not show Welcome next time" when program starts every time while it's configuration value is to show it?

**Comment by crisistotal2014** [comment]
Work done! I'll hope you like way I implemented.

**Comment by ericmore** [comment]
I put this into configuration.xml , user can manully config it to be true/false 
<entry key="ShowWelcomePage">false</entry>
popup a dialog seems a little troublesome to end user. Close it now.
