### ISSUE TITLE
Save main window size

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#7]
Hi Eric!
Can I implement saving of main window size in configuration? Many people works with special sizes (having window on top of screen, or down) and I think will be usefull to save this size for future executions.

**Comment by crisistotal2014** [comment]
Ok, thank you. I'll try to implement a good mechanism.

**Comment by crisistotal2014** [comment]
Done and uploaded to "dev" branch!
Please, check out.

**Comment by ericmore** [comment]
Cool work~ Verified, close it
