### ISSUE TITLE
"Hostname" and "Protocol" fields has been dissapeared on "dev" branch

### ISSUE THREAD

**Issue by crisistotal2014** [ericmore/SmartPutty#8]
Hello Eric!
I've checked out "dev" branch and I've detected "Hostname" and "Protocol" fields has dissapeared on upper bar.
Can you re-add it?

(Feel free to close this issue when done)

**Comment by crisistotal2014** [comment]
Hi!
Can you re-enable it, please?

**Comment by ericmore** [comment]
Hi Carlos, I've enable the hostname/port item in connection bar.  Could you please verify if it works now ?

**Comment by crisistotal2014** [comment]
Thank you for re-enable.
But I think we implemented port change when protocol was changed.
